version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    links:
#      - mongo
#    depends_on:
#      - mongo
#    restart: on-failure


volumes:
  postgres: